# Generated by Django 2.1.2 on 2019-02-08 13:35

from django.db import migrations, models
import django.db.models.deletion
import sindanglaya.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kavling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kavling', models.CharField(max_length=100)),
                ('hook', models.IntegerField(default=0)),
                ('harga_standar', models.IntegerField(default=0)),
                ('booking', models.IntegerField(default=0)),
                ('uang_muka', models.IntegerField(default=0)),
                ('klt', models.FloatField(default=0)),
                ('biaya_strategis', models.IntegerField(default=0)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kegiatan_Marketingnya',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul_kegiatan', models.CharField(max_length=100)),
                ('deskripsi', models.TextField(max_length=100)),
                ('waktu', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Marketer',
            fields=[
                ('id', models.CharField(default=sindanglaya.models.create_id, editable=False, max_length=100, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('no_hp', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kostumer',
            fields=[
                ('nama', models.CharField(max_length=100)),
                ('kavling', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='pemohon', serialize=False, to='sindanglaya.Kavling')),
                ('no_ktp', models.CharField(max_length=30)),
                ('tempat_lahir', models.CharField(max_length=100)),
                ('tanggal_lahir', models.DateField()),
                ('alamat', models.CharField(max_length=100)),
                ('no_hp', models.CharField(max_length=100)),
                ('pekerjaan', models.CharField(blank=True, choices=[('pns', 'PNS'), ('pegawai swasta', 'Pegawai Swasta'), ('wiraswasta', 'Wiraswasta')], max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('nama_perusahaan', models.CharField(blank=True, max_length=100, null=True)),
                ('alamat_perusahaan', models.TextField(blank=True, max_length=100, null=True)),
                ('nama_atasan', models.CharField(blank=True, max_length=100, null=True)),
                ('no_hp_atasan', models.CharField(blank=True, max_length=100, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('nama_pasangan', models.CharField(blank=True, max_length=100, null=True)),
                ('no_ktp_pasangan', models.CharField(blank=True, max_length=30, null=True)),
                ('tempat_lahir_pasangan', models.CharField(blank=True, max_length=100, null=True)),
                ('tanggal_lahir_pasangan', models.CharField(blank=True, max_length=10, null=True)),
                ('alamat_pasangan', models.TextField(blank=True, max_length=100, null=True)),
                ('pekerjaan_pasangan', models.CharField(blank=True, max_length=100, null=True)),
                ('no_hp_pasangan', models.CharField(blank=True, max_length=100, null=True)),
                ('nama_keluarga', models.CharField(blank=True, max_length=100, null=True)),
                ('no_ktp_keluarga', models.CharField(blank=True, max_length=30, null=True)),
                ('alamat_keluarga', models.TextField(blank=True, max_length=100, null=True)),
                ('no_hp_keluarga', models.CharField(blank=True, max_length=100, null=True)),
                ('ktp', models.ImageField(blank=True, default='tidak_ada.jpg', null=True, upload_to=sindanglaya.models.path_and_rename)),
                ('kartu_keluarga', models.ImageField(blank=True, default='tidak_ada.jpg', null=True, upload_to=sindanglaya.models.path_and_rename)),
                ('buku_nikah', models.ImageField(blank=True, default='tidak_ada.jpg', null=True, upload_to=sindanglaya.models.path_and_rename)),
                ('npwp', models.ImageField(blank=True, default='tidak_ada.jpg', null=True, upload_to=sindanglaya.models.path_and_rename)),
                ('keteranganpenghasilan', models.ImageField(blank=True, default='tidak_ada.jpg', null=True, upload_to=sindanglaya.models.path_and_rename)),
                ('foto', models.ImageField(blank=True, default='tidak_ada.jpg', null=True, upload_to=sindanglaya.models.path_and_rename)),
                ('rekening_koran', models.ImageField(blank=True, default='tidak_ada.jpg', null=True, upload_to=sindanglaya.models.path_and_rename)),
                ('sk_bekerja', models.ImageField(blank=True, default='tidak_ada.jpg', null=True, upload_to=sindanglaya.models.path_and_rename)),
                ('sliip_gaji', models.ImageField(blank=True, default='tidak_ada.jpg', null=True, upload_to=sindanglaya.models.path_and_rename)),
                ('kartu_pegawai', models.ImageField(blank=True, default='tidak_ada.jpg', null=True, upload_to=sindanglaya.models.path_and_rename)),
                ('sku_skhu', models.ImageField(blank=True, default='tidak_ada.jpg', null=True, upload_to=sindanglaya.models.path_and_rename)),
                ('neraca', models.ImageField(blank=True, default='tidak_ada.jpg', null=True, upload_to=sindanglaya.models.path_and_rename)),
                ('foto_usaha', models.ImageField(blank=True, default='tidak_ada.jpg', null=True, upload_to=sindanglaya.models.path_and_rename)),
                ('dc', models.BooleanField(default=False)),
                ('tanggal_dc', models.DateTimeField(blank=True, null=True)),
                ('ket_dc', models.TextField(blank=True, null=True)),
                ('slik', models.BooleanField(default=False)),
                ('tanggal_slik', models.DateTimeField(blank=True, null=True)),
                ('ket_slik', models.TextField(blank=True, null=True)),
                ('wawancara', models.BooleanField(default=False)),
                ('tanggal_wawancara', models.DateTimeField(blank=True, null=True)),
                ('ket_wawancara', models.TextField(blank=True, null=True)),
                ('ots', models.BooleanField(default=False)),
                ('tanggal_ots', models.DateTimeField(blank=True, null=True)),
                ('ket_ots', models.TextField(blank=True, null=True)),
                ('sp3k', models.BooleanField(default=False)),
                ('tanggal_sp3k', models.DateTimeField(blank=True, null=True)),
                ('ket_sp3k', models.TextField(blank=True, null=True)),
                ('akad', models.BooleanField(default=False)),
                ('tanggal_akad', models.DateTimeField(blank=True, null=True)),
                ('ket_akad', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='kegiatan_marketingnya',
            name='marketer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sindanglaya.Marketer'),
        ),
    ]
