# Generated by Django 2.1.2 on 2019-02-19 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pprg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kavling',
            name='plafon',
            field=models.IntegerField(default=0),
        ),
    ]
